name: App Restart

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  restart:
    runs-on: ubuntu-latest
    
    steps:
      - name: hello
      - run: |
          pm2 flush 
          pm2 kill
          pm2 start
      
