name: App Restart

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    
    steps:
      - name: setup credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: restart step connect
        uses: appleboy/ssh-action@master
        with:
          host: 172.31.19.128
          username: ubuntu
          key: ${{ secrets.NAGARRO_PEM }}
          port: 22
          script: whoami
        
      - name: restart step
        run: |
          echo "----- PM2 Restarted--------------"
          # ssh -o StrictHostKeyChecking=no ubuntu@172.31.19.128
          # pm2 flush 
          # pm2 kill
          # pm2 start
      
