name: App Restart

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    
    steps:
      - name: setup credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::100889562744:role/storefront-github-action
          aws-region: ap-southeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200
          role-session-name: MySessionName
          
      - name: restart step     
        run: |
          echo "----- PM2 Restarted--------------"
          ssh -o StrictHostKeyChecking=no ubuntu@172.31.19.128
          pm2 flush 
          pm2 kill
          pm2 start
      
