name: App Restart

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    
    steps:
      - name: setup credentials
      - uses: aws-actions/configure-aws-credentials@v1
      - with:
          role-to-assume: arn:aws:iam::100889562744:role/jenkins-role
          aws-region: ap-southeast-2
          
      - name: restart step     
      - run: |
          echo "----- PM2 Restarted--------------"
      
