name: App Restart

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    
    steps:
      - name: setup credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::100889562744:role/storefront-github-action
      
